"""initial schema

Revision ID: 672e96a32312
Revises:
Create Date: 2026-08-28 19:41:13.412523
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "672e96a32312"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cve_cache",
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cpe_matches", sa.JSON(), nullable=False),
        sa.Column("cwe_ids", sa.JSON(), nullable=False),
        sa.Column("reference_urls", sa.JSON(), nullable=False),
        sa.Column("published_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("cve_id"),
    )
    op.create_table(
        "intel_source_state",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target_raw", sa.Text(), nullable=False),
        sa.Column("target_host", sa.String(length=255), nullable=False),
        sa.Column("target_ip", sa.String(length=45), nullable=True),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("profile", sa.String(length=32), nullable=False),
        sa.Column("modules_run", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scans_target_host"), ["target_host"], unique=False)

    op.create_table(
        "cpe_index",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vendor", sa.String(length=128), nullable=False),
        sa.Column("product", sa.String(length=128), nullable=False),
        sa.Column("version_start", sa.String(length=64), nullable=True),
        sa.Column("version_end", sa.String(length=64), nullable=True),
        sa.Column("version_exact", sa.String(length=64), nullable=True),
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["cve_id"], ["cve_cache.cve_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cpe_index", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cpe_index_cve_id"), ["cve_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cpe_index_product"), ["product"], unique=False)
        batch_op.create_index(batch_op.f("ix_cpe_index_vendor"), ["vendor"], unique=False)

    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scan_id", sa.String(length=36), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cve_ids", sa.JSON(), nullable=False),
        sa.Column("cwe_ids", sa.JSON(), nullable=False),
        sa.Column("attack_techniques", sa.JSON(), nullable=False),
        sa.Column("sigma_rule_ids", sa.JSON(), nullable=False),
        sa.Column("atomic_tests", sa.JSON(), nullable=False),
        sa.Column("elastic_rules", sa.JSON(), nullable=False),
        sa.Column("prevalence_score", sa.Float(), nullable=True),
        sa.Column("epss_score", sa.Float(), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=False),
        sa.Column("reference_urls", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("service", sa.String(length=64), nullable=True),
        sa.Column("raw_data_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_severity"), ["severity"], unique=False)

    op.create_table(
        "raw_data",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scan_id", sa.String(length=36), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("data_type", sa.String(length=32), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=16), nullable=True),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("raw_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_raw_data_data_type"), ["data_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_data_scan_id"), ["scan_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_data_scan_id"))
        batch_op.drop_index(batch_op.f("ix_raw_data_data_type"))

    op.drop_table("raw_data")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_severity"))
        batch_op.drop_index(batch_op.f("ix_findings_scan_id"))

    op.drop_table("findings")
    with op.batch_alter_table("cpe_index", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cpe_index_vendor"))
        batch_op.drop_index(batch_op.f("ix_cpe_index_product"))
        batch_op.drop_index(batch_op.f("ix_cpe_index_cve_id"))

    op.drop_table("cpe_index")
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scans_target_host"))

    op.drop_table("scans")
    op.drop_table("intel_source_state")
    op.drop_table("cve_cache")
    # ### end Alembic commands ###
